# Generated by Django 3.2 on 2024-01-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.UUIDField(default='3009bea3-dba4-4b02-af42-50bcaf94e196', editable=False, primary_key=True, serialize=False),
        ),
    ]
