# Generated by Django 3.2 on 2024-01-22 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_alter_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.UUIDField(default='60f2b165-e84d-4501-8fb4-17db6c9cbc54', editable=False, primary_key=True, serialize=False),
        ),
    ]
