# Generated by Django 3.2 on 2024-01-22 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_alter_empresa_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='id',
            field=models.UUIDField(default='74c5e99b-1e5d-45d4-8565-ab33ac627561', editable=False, primary_key=True, serialize=False),
        ),
    ]
