# Generated by Django 3.2 on 2024-01-22 23:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('departamentos', '0002_rename_departamentos_departamento'),
        ('empresa', '0002_alter_empresa_id'),
        ('funcionarios', '0004_auto_20240122_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionarios',
            name='departamentos',
            field=models.ManyToManyField(to='departamentos.Departamento'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.empresa'),
        ),
        migrations.AddField(
            model_name='funcionarios',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='funcionarios',
            table='rh_funcionario',
        ),
    ]
